sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - docker build -t tibero6-test-build .
      - docker images
      - docker tag travis-ci-build-stages-demo $DOCKER_USERNAME/travis-ci-build-stages-demo
